name: NAFNet-SIDD-finetune-width64-8k
model_type: ImageRestorationModel
scale: 1
num_gpu: 1
manual_seed: 10

datasets:
  train:
    name: SIDD-Finetune-Train
    type: PairedImageDataset
    dataroot_gt: ./datasets/SIDD/train/gt
    dataroot_lq: ./datasets/SIDD/train/lq
    gt_size: 256
    use_flip: true
    use_rot: true
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 10
    mean: [0, 0, 0]
    std: [1, 1, 1]
  val:
    name: SIDD-Finetune-Val
    type: PairedImageDataset
    dataroot_gt: ./datasets/SIDD/val_backup_20260520/gt
    dataroot_lq: ./datasets/SIDD/val_backup_20260520/lq

network_g:
  type: NAFNet
  width: 64
  enc_blk_nums: [2, 2, 4, 8]
  middle_blk_num: 12
  dec_blk_nums: [2, 2, 2, 2]

path:
  pretrain_network_g: ./experiments/pretrained_models/NAFNet-SIDD-width64.pth
  strict_load_g: true
  resume_state: null
  root: /home/luluboy/projects/vrdl_final/code/NAFNet
  experiments_root: /home/luluboy/projects/vrdl_final/code/NAFNet/experiments/NAFNet-SIDD-finetune-width64-8k
  models: /home/luluboy/projects/vrdl_final/code/NAFNet/experiments/NAFNet-SIDD-finetune-width64-8k/models
  training_states: /home/luluboy/projects/vrdl_final/code/NAFNet/experiments/NAFNet-SIDD-finetune-width64-8k/training_states

train:
  optim_g:
    type: AdamW
    lr: !!float 5e-5
    weight_decay: 0.0
    betas: [0.9, 0.999]
  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 20000
    eta_min: 1.0e-6
  total_iter: 20000
  warmup_iter: 500
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1.0
    reduction: mean
  use_amp: true

val:
  val_freq: 999999
  save_img: false
  use_image: false
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

evaluation:
  freq: 0

logger:
  print_freq: 100
  save_checkpoint_freq: 2000
  use_tb_logger: false

dist_params:
  backend: nccl
  port: 29500

is_train: true
dist: false
rank: 0
world_size: 1